### ISSUE TITLE
Many mirrors have an incompatible interface

### ISSUE THREAD

**Issue by bignellrp** [vikstrous/pirate-get#134]
Even on working mirror urls getting blocked mirror detected.

**Comment by rnhmjoj** [comment]
Which pirate-get version do you have?

I guess this is the same issue as: https://github.com/vikstrous/pirate-get/issues/131#issuecomment-605680880

**Comment by bignellrp** [comment]
Python 3.6
Pirate-get 0.3.4

**Comment by bignellrp** [comment]
mirror = https://pirateproxy.name https://thepirate-bay.org/

pirate-get ubuntu
Trying https://pirateproxy.name... Failed  (Cloudflare protected)
Trying https://thepirate-bay.org/... Failed  (Blocked mirror detected.)
Trying https://pirateproxy.name... Failed  (Cloudflare protected)
Trying https://tpb16.ukpass.co... Failed  (Cloudflare protected)
Trying https://tpb.sadzawka.tk... Failed  ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte)
Trying https://www.tpbay.win... Failed  ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte)
Trying https://thepiratebay.vip... Failed  (HTTP Error 403: Forbidden)
Trying https://piratenow.xyz... Failed  ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte)
Trying https://piratebayztemzmv.onion.pet... Failed  (Blocked mirror detected.)
Trying https://piratebayztemzmv.onion.ly/... Failed  (Blocked mirror detected.)
No more available mirrors :(

**Comment by bignellrp** [comment]
RarBG gives a different error:

pirate-get ubuntu
Trying https://rarbg.to/... Failed  ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte)

**Comment by rnhmjoj** [comment]
Uhm, all these mirrors are not actually mirrors of the pirate bay.
They are detected as blocked mirror because the queries pirate-get does for a search, like
```
https://thepirate-bay.org/search/keyword/0/7/0
```
returns an empty (0 bytes) page. Other queries return an error 404. I can't get the unicode decode errors you see, I get another 404 error instead.
I wonder how and why they are exposing the site though a different interface instead of simply mirroring the site, which is trivial to do. 

Anyway, to handle these new mirrors we would basically have to rewrite pirate-get to support these interface. I don't think it's gonna happen because there is no guarantee this interface is stable and I don't really have time for such a large rewrite.

Right now the only option to avoid this mirror madness is to use the tor hidden service of tpb.

**Comment by rnhmjoj** [comment]
So, I found out that the pirate bay has been secretly using a nice and shiny JSON API for a while.
Basically the website is rendered client-side using the API and a script. This makes scraping the HTML unecessary (thank god) so it was so much easier to implement. 
I hacked together the support for the new API in the https://github.com/vikstrous/pirate-get/commits/api branch. It should be fairly usable already but I have to fix all the broken tests.

**Comment by vikstrous** [comment]
Thank you! I'll try to take a look this weekend.

**Comment by rnhmjoj** [comment]
I managed to fix most of the tests. The only features that are missing are sorting and pagination, and "browse" mode. Pagination and sorting could probably be done client-side, but I don't actually know what "browse" mode was supposed to do because I've never used it.

**Comment by eyalzek** [comment]
@rnhmjoj I just tested the `api` branch after `pirate-get` failing for me with error like https://github.com/vikstrous/pirate-get/issues/134#issuecomment-626212075 for months now - and it works perfectly!
