### ISSUE TITLE
Allow more options to be set in the config file

### ISSUE THREAD

**Issue by vikstrous** [vikstrous/pirate-get#16]
One useful example would be -t because transmission users want to always use transmission and they shouldn't need to specify that every time.

**Comment by Rnhmjoj** [comment]
I have added to the config the main command line options.
I have given priority to command line arguments so that options in the config can be overridden by the arguments.
https://github.com/vikstrous/pirate-get/commit/3ef1c89a569bc95740a0a622f2144139c68ccfc0
https://github.com/vikstrous/pirate-get/commit/f984a474ce933ecf8fc5bbdccbe7f79c68e0c6d6

**Comment by vikstrous** [comment]
Looks good. I think we can close this for now.
